{
 "title": "Pizza-Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage%",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg(last_over_time(({source=~\"jwt-pizza-service\", metric=\"system\"} | json | unwrap cpuUsagePercent)[5m]))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg(last_over_time(({source=~\"jwt-pizza-service\", metric=\"system\"} | json | unwrap memoryUsagePercent)[5m]))"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg(last_over_time(({source=\"jwt-pizza-service\", metric=\"auth\"} | json | unwrap activeUsers)[5m]))",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "HTTP Requests / Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg(sum_over_time({source=~\"jwt-pizza-service(-dev)?\", metric=\"http\"} | json | __error__=\"\" | unwrap DELETE [5m]))"
    },
    {
     "direction": "backward",
     "expr": "avg(sum_over_time({source=~\"jwt-pizza-service(-dev)?\", metric=\"http\"} | json | __error__=\"\" | unwrap GET [5m]))"
    },
    {
     "direction": "backward",
     "expr": "avg(sum_over_time({source=~\"jwt-pizza-service(-dev)?\", metric=\"http\"} | json | __error__=\"\" | unwrap POST [5m]))"
    },
    {
     "direction": "backward",
     "expr": "avg(sum_over_time({source=~\"jwt-pizza-service(-dev)?\", metric=\"http\"} | json | __error__=\"\" | unwrap PUT [5m]))"
    },
    {
     "direction": "backward",
     "expr": "avg(sum_over_time({source=~\"jwt-pizza-service(-dev)?\", metric=\"http\"} | json | __error__=\"\" | unwrap total [5m]))"
    }
   ]
  },
  {
   "title": "Authentication attempts/minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg(sum_over_time({source=~\"jwt-pizza-service(-dev)?\", metric=\"auth\"} | json | __error__=\"\" | unwrap success [5m]))"
    },
    {
     "direction": "backward",
     "expr": "avg(sum_over_time({source=~\"jwt-pizza-service(-dev)?\", metric=\"auth\"} | json | __error__=\"\" | unwrap failure [5m]))"
    }
   ]
  },
  {
   "title": "CPU and Memory Usage %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg(last_over_time(({source=~\"jwt-pizza-service\", metric=\"system\"} | json | unwrap cpuUsagePercent)[5m]))",
     "legendFormat": "CPU Usage"
    },
    {
     "direction": "backward",
     "expr": "avg(last_over_time(({source=~\"jwt-pizza-service(-dev)?\", metric=\"system\"} | json | unwrap memoryUsagePercent)[5m]))",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Service Endpoint Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg(sum by (endpoint) (\n  avg_over_time(\n    {source=~\"jwt-pizza-service\", metric=\"latency\"}\n    | json\n    | label_format endpoint=\"{{.endpoint}}\"\n    | unwrap averageLatencyMs [5m]\n  )\n))",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Pizzas (sold/failures/revenue)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "avg(sum_over_time({source=~\"jwt-pizza-service(-dev)?\", metric=\"pizza\"} | json | __error__=\"\" | unwrap sold [5m]))",
     "legendFormat": "Sold/min"
    },
    {
     "direction": "backward",
     "expr": "avg(sum_over_time({source=~\"jwt-pizza-service(-dev)?\", metric=\"pizza\"} | json | __error__=\"\" | unwrap failures [5m]))",
     "legendFormat": "Failures/min"
    },
    {
     "direction": "backward",
     "expr": "avg(sum_over_time({source=~\"jwt-pizza-service(-dev)?\", metric=\"pizza\"} | json | __error__=\"\" | unwrap revenue [5m]))",
     "legendFormat": "Revenue/min"
    }
   ]
  }
 ]
}